server:
  port: 81
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: starbox7
    password: starbox7
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
